name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - Fundamentals
          - Databases/MongoDB
          - Databases/postgresql
          - Docker
          - Projects/go-prometheus/my-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build ${{ matrix.module }}
        working-directory: ${{ matrix.module }}
        run: |
          echo "üîß Building module: ${{ matrix.module }}"
          go mod tidy
          go build -v ./...

      - name: Run tests for ${{ matrix.module }}
        working-directory: ${{ matrix.module }}
        run: |
          echo "üß™ Running tests for module: ${{ matrix.module }}"
          go test -v ./... || echo "‚ö†Ô∏è No tests found in ${{ matrix.module }}"
